### ISSUE TITLE
-w Write to a file... not writing to a file

### ISSUE THREAD

**Issue by steve3p0** [GrammaticalFramework/gftest#11]
When I run the following test, nothing is written to a file:

`gftest -g Lang -l Eng --show-coercions -w `

This does not write to a file.  It Just reports:
Wrote results in LangEng_VP.org
Wrote results in LangEng_VP.org
Wrote results in LangEng_VP.org

The file LangEng_.org is empty and the output is actually sent to stdout.

**Comment by inariksit** [comment]
@steve3p0 thanks for the report (and thanks for using gftest :-D)! It's just that I didn't bother make `-w` interact with other options that `-f` and `-c`.

As of [#12](https://github.com/GrammaticalFramework/gftest/pull/12) it's writing to a file consistently with all options.
